# Base de datos H2 (memoria)
spring.datasource.url=jdbc:h2:mem:fedelabsv4;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# SQL Init - ¡ESTAS 2 LÍNEAS SON CRUCIALES!
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true

# Logging más detallado
logging.level.com.fedelabsv4=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Cache deshabilitado para desarrollo
spring.cache.type=none

# DevTools activado
spring.devtools.restart.enabled=true
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}