package com.fedelabsv4.service;

import com.fedelabsv4.model.Apunte;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

@Service
public class ApunteService {

    private final List<Apunte> apuntes = new ArrayList<>();
    private final AtomicLong idCounter = new AtomicLong(1);

    public ApunteService() {
       
      String[][] data = {
    {"La belleza del minimalismo", "Diseño", "El minimalismo no es ausencia, sino precisión. En diseño, cada elemento sobra si no cumple una función clara. Esta filosofía reduce el ruido visual y permite que el mensaje respire. Al eliminar adornos innecesarios, se gana claridad, velocidad de carga y una experiencia más agradable para el usuario. El minimalismo exige disciplina: hay que decidir qué se queda y qué se descarta. No se trata de vacío, sino de espacio para lo esencial. Grandes maestros como Dieter Rams o John Pawson lo aplicaron en producto y arquitectura. Hoy, en interfaces digitales, el minimalismo mejora la usabilidad y la accesibilidad. Menos es más, pero siempre que ese 'menos' esté bien pensado."},
    {"Spring Boot en producción", "Tecnología", "Llevar Spring Boot a producción va más allá de ejecutar un JAR. Hay que configurar perfiles (dev, test, prod), externalizar propiedades con Config Server o variables de entorno, y gestionar secretos con Vault. Monitoreo con Actuator, métricas en Prometheus y tracing con Zipkin son imprescindibles. También conviene usar logs estructurados (JSON) para facilitar su búsqueda en ELK. El manejo de conexiones a BD con HikariCP y la preparación para fallos (retries, circuit breakers con Resilience4j) evitan caídas. Por último, un despliegue gradual (blue/green o canary) reduce riesgos. Spring Boot es potente, pero en producción necesita la misma madurez que cualquier otra herramienta crítica."},
    {"Patrones de arquitectura limpia", "Programación", "La arquitectura limpia (Clean Architecture) propuesta por Robert C. Martin separa el código en capas concéntricas: entidades, casos de uso, interfaces y frameworks. Las dependencias apuntan hacia adentro, aislando la lógica de negocio de detalles externos como bases de datos o APIs. Esto facilita pruebas unitarias, cambios de tecnología y mantenimiento a largo plazo. Aunque requiere más archivos y estructura inicial, la ganancia en claridad y desacoplamiento es enorme. Combinada con principios SOLID e inyección de dependencias, se convierte en una base sólida para aplicaciones que esperan crecer. No es magia, pero ordena el caos."},
    {"Reflexiones sobre la creatividad", "Personal", "La creatividad no aparece por arte de magia; se entrena. Es una mezcla de observación, curiosidad y el hábito de conectar ideas dispares. A menudo se confunde con talento innato, pero en realidad es perseverancia: fallar mucho, corregir y volver a intentar. Crear algo nuevo da miedo, porque expone nuestra vulnerabilidad. Sin embargo, es justo ahí donde ocurre el aprendizaje real. Rodéate de estímulos diversos, lee sobre temas que no dominas, toma descansos y permite el aburrimiento. Las mejores ideas llegan cuando no estás forzándolas. Sé amable contigo mismo en el proceso."},
    {"Tipografía y jerarquía visual", "Diseño", "La tipografía es la voz del diseño. Elegir bien las fuentes (serif vs sans‑serif, pesos, tamaños) define el tono y la legibilidad. La jerarquía visual ordena la información: tamaños grandes para títulos, intermedios para subtítulos, pequeños para el cuerpo. También influyen el espaciado (interletraje, interlineado) y el contraste de color. Una buena jerarquía guía la mirada del usuario de lo más importante a lo secundario sin que él lo note. En la web, además hay que pensar en la accesibilidad (tamaños relativos en rem, alto contraste) y en la respuesta móvil. La tipografía no es solo estética: es funcionalidad y claridad."},
    {"APIs RESTful bien diseñadas", "Programación", "Una API RESTful bien diseñada es predecible, consistente y autodescriptiva. Usa sustantivos en lugar de verbos en los endpoints (ej. /usuarios en vez de /getUsuarios). Aprovecha los códigos de estado HTTP correctamente: 200 para éxito, 201 para creación, 400 para error del cliente, 401 no autorizado, 404 no encontrado, 500 para error del servidor. La versión se puede indicar en la URL (/v1/usuarios) o en el header Accept. Filtros, paginación y ordenamiento se manejan con query params (limit, offset, sort). Documenta con OpenAPI/Swagger. Además, no olvides la idempotencia para métodos PUT/DELETE. Una API limpia ahorra horas de frustración."},
    {"El poder del espacio negativo", "Diseño", "El espacio negativo (o blanco) no es desperdicio: es respiro. En diseño gráfico, digital o arquitectónico, los espacios vacíos permiten que los elementos importantes destaquen. Sin ellos, todo compite y el usuario se siente abrumado. Un buen uso del margen, el relleno y la separación entre secciones mejora la legibilidad y la comprensión. Grandes marcas como Apple o Muji construyen su identidad con espacios generosos. También influye en la percepción de lujo y sofisticación. Al maquetar, pregunta: '¿Puedo ampliar los márgenes? ¿Estoy llenando solo por miedo al vacío?' El espacio negativo es una herramienta activa, no un hueco pasivo."},
    {"Notas sobre productividad", "Personal", "La productividad real no es hacer más cosas en menos tiempo, sino hacer las cosas correctas con la energía adecuada. Identifica tus horas de mayor foco (mañana o noche) y protege ese bloque. Usa técnicas como Pomodoro o time blocking. Aprende a decir 'no' a tareas que no aportan a tus metas. La multitarea es un mito: el cerebro cambia de contexto y pierde eficiencia. Descansar también produce: caminar, dormir bien, tomar pausas. Herramientas como Trello o Notion ayudan, pero no resuelven la procrastinación. La productividad es ante todo autoconocimiento y hábitos sostenibles, no presión constante."},
    {"Microservicios en Java", "Tecnología", "Java es un pilar para microservicios gracias a frameworks como Spring Boot, Micronaut o Quarkus. La ventaja es el despliegue independiente de cada servicio, escalabilidad granular y equipos autónomos. Pero también trae complejidad: gestión de transacciones distribuidas (Saga pattern), descubrimiento de servicios (Eureka, Consul), comunicación asíncrona (RabbitMQ, Kafka) y monitoreo agregado. En Java, Spring Cloud facilita patrones como circuit breaker, gateway y config server. No conviene usar microservicios para proyectos pequeños o equipos sin experiencia en DevOps; a veces un monolito bien modularizado es mejor. Evaluar con cabeza fría."},
    {"Color y composición", "Diseño", "El color emociona, la composición ordena. La teoría del color (círculo cromático, armonías complementarias, análogas, triádicas) ayuda a crear paletas coherentes. La temperatura (cálidos vs fríos) afecta la percepción de cercanía o distancia. La composición sigue reglas como la de los tercios, la sección áurea o el peso visual. Colocar elementos grandes cerca del centro da estabilidad; asimetrías generan dinamismo. En diseño UI, el contraste de color es clave para accesibilidad (WCAG). Combinar bien color y composición transforma un diseño amateur en uno profesional. Herramientas como Adobe Color o Coolors pueden ayudar, pero el ojo entrenado es insustituible."},
    {"Testing efectivo en backend", "Programación", "El testing en backend no es opcional. Pruebas unitarias (JUnit, Mockito) verifican cada clase aislada. Pruebas de integración comprueban que módulos (repositorios, servicios externos) funcionen juntos. Y pruebas end‑to‑end validan flujos completos con el contexto real (base de datos, colas). Un buen suite de tests aumenta la confianza para refactorizar y desplegar rápido. También sirven como documentación viva del sistema. Pirámide de tests: muchas unitarias, menos de integración, pocas E2E. No olvides los tests de contrato (Pact) si tienes microservicios. Automatiza todo en CI/CD. El código no probado es código legacy desde el día 1."},
    {"Hábitos de un desarrollador", "Personal", "Un buen desarrollador no solo escribe código; lee código ajeno, documenta, pregunta y comparte. Hábito 1: leer al menos una pull request al día para aprender. Hábito 2: tomar descansos cada 50 minutos para evitar fatiga mental. Hábito 3: hacer refactors pequeños continuamente, no acumular deuda técnica. Hábito 4: escribir tests antes o junto al código (TDD). Hábito 5: llevar un registro de errores recurrentes para no repetirlos. Hábito 6: enseñar lo que aprendes, así lo afianzas. La paciencia y la resiliencia ante problemas complejos son tan importantes como la lógica. Programar es un arte que se mejora con disciplina diaria."},
    {"Diseño de sistemas escalables", "Tecnología", "Escalar no es solo añadir servidores. Hay que pensar en bases de datos (replicación, particionamiento, sharding), cachés (Redis, CDN), colas (RabbitMQ, Kafka), balanceadores de carga y sistemas de mensajería asíncrona. También en cómo manejar fallos parciales: circuit breakers, retries con backoff, timeouts. Un sistema escalable suele ser eventualmente consistente, no transaccional distribuido (a menos que uses algo como Spanner). Además, el monitoreo y la observabilidad (logs, métricas, traces) son indispensables para entender cuellos de botella. Diseñar para escalar desde el principio cuesta, pero rediseñar después duele más. La simplicidad es la máxima escalabilidad."},
    {"Lecturas que cambiaron mi forma de pensar", "Personal", "Libros como 'Pensar rápido, pensar despacio' de Kahneman me enseñaron sobre sesgos cognitivos. 'El diseño de las cosas cotidianas' de Norman cambió mi visión de la usabilidad. 'Clean Code' de Martin me hizo ver el código como comunicación humana. 'Start with Why' de Sinek me dio una brújula para proyectos. 'Sapiens' de Harari amplió mi contexto histórico. Cada lectura modifica pequeñas estructuras mentales. Lo importante no es solo leer, sino reflexionar y aplicar. También recomiendo 'El hombre en busca de sentido' de Frankl. Una buena biblioteca personal es un taller de transformación continua."},
    {"Grids y layouts modernos en CSS", "Diseño", "CSS Grid y Flexbox revolucionaron el diseño web. Grid es ideal para layouts bidimensionales (filas y columnas), mientras Flexbox para una dimensión (fila o columna). Con Grid puedes crear mosaicos complejos, superposiciones y rejillas responsivas sin hacks de floats o tablas. Propiedades como grid-template-areas hacen el código legible. Además, puedes combinar ambas tecnologías: usar Grid para la macro estructura y Flexbox para componentes internos. Los layouts modernos son fluidos con minmax(), fr units y media queries. También existe Subgrid (ya soportado) para anidar rejillas. Dominar estos sistemas es obligatorio para cualquier maquetador frontend hoy."},
    {"Principios SOLID aplicados", "Programación", "SOLID no es una moda, es una guía para código mantenible. Responsabilidad única (S): una clase con un solo motivo para cambiar. Abierto/cerrado (O): abiertas a extensión, cerradas a modificación. Sustitución de Liskov (L): subtipos deben poder reemplazar a su tipo base. Segregación de interfaces (I): interfaces pequeñas y específicas. Inversión de dependencias (D): depender de abstracciones, no de concreciones. En Java, aplicarlos reduce el acoplamiento y facilita pruebas. Por ejemplo, inyectar interfaces en lugar de implementaciones concretas permite cambiar de base de datos sin tocar la lógica de negocio. No son reglas absolutas, pero violarlos suele traer deuda técnica a largo plazo."},
    {"La importancia del descanso", "Personal", "El descanso no es pérdida de tiempo, es inversión en rendimiento. Dormir menos de 7 horas afecta la creatividad, la memoria y la capacidad de resolver problemas. También genera errores y desmotivación. Descansar incluye vacaciones, pausas activas, desconexión digital y ocio sin culpa. El cerebro consolida lo aprendido durante el sueño. Grandes creadores como Einstein o Darwin dormían bien. Además, el descanso previene el burnout, una epidemia en tecnología. Aprender a parar es una habilidad. Programar un 'día sin pantallas' a la semana puede transformar tu claridad mental. Haz del descanso una prioridad no negociable."},
    {"Docker para desarrolladores Java", "Tecnología", "Docker empaqueta tu app Java con todo su entorno: JVM, variables, dependencias nativas. Esto elimina el 'en mi máquina funciona'. Un Dockerfile típico usa una imagen base como openjdk:17, copia el JAR y expone el puerto. Los multi‑stage builds reducen el tamaño final. Con docker‑compose puedes levantar también la base de datos, Redis y otros servicios. Para desarrollo, usa volúmenes para recargar clases en caliente (con Spring DevTools). Además, herramientas como Jib (de Google) generan imágenes optimizadas sin Dockerfile. Docker es el primer paso hacia contenedores en Kubernetes. No requiere magia, solo práctica y buenas prácticas de seguridad."},
    {"Branding personal en la web", "Negocios", "Tu marca personal es lo que otros dicen de ti cuando no estás presente. En la web, se construye con coherencia: mismo nombre y foto en todas redes, un sitio web propio (aunque sea simple), un blog o newsletter donde compartas tu expertise. También influye la calidad de tus interacciones: responder comentarios, dar crédito, ser útil sin esperar nada a cambio. El branding no es postureo, es autenticidad visible. Puedes elegir un nicho (desarrollo, diseño, negocios) y aportar valor constante. Con el tiempo, llegan oportunidades laborales, charlas, colaboraciones. No esperes a ser 'experto' para empezar; empieza pequeño y mejora con cada publicación."},
    {"Estrategias de caché en aplicaciones", "Tecnología", "La caché acelera respuestas y reduce carga en bases de datos. Estrategias: caché local (Caffeine, Guava) para datos poco cambiantes por servidor; caché distribuida (Redis, Memcached) para compartir entre instancias. Políticas de invalidación: TTL (tiempo de vida), escritura directa (write‑through), escritura diferida (write‑behind) o invalidación manual. También existe caché de consultas (Spring @Cacheable), caché HTTP (CloudFront, Varnish) y caché de objetos pesados. Pero la caché introduce complejidad: datos obsoletos (stale reads), consistencia eventual, y la avalancha (muchas claves expiran juntas). Úsala donde realmente se necesite. La mejor caché es la que no tienes que invalidar, pero eso casi nunca ocurre."},
    {"Cómo dar feedback efectivo", "Personal", "Dar feedback es un arte. La técnica SBI (Situación, Comportamiento, Impacto) es efectiva: describe el contexto, la acción concreta y el efecto que tuvo. Evita etiquetas ('eres desorganizado') y habla desde tu perspectiva ('cuando la entrega se retrasó, el equipo tuvo que reajustar horarios'). Para feedback positivo, sé específico ('me gustó cómo manejaste la reunión con el cliente, porque lograste clarificar los requisitos'). Para feedback constructivo, ofrece sugerencias y muestra disposición a ayudar. También importa el momento: privado, calmado y con tiempo para dialogar. El feedback no es crítica personal; es información para mejorar. Escuchar también es parte del proceso."},
    {"Diseño centrado en el usuario", "Diseño", "El diseño centrado en el usuario (UCD) pone a las personas en el centro del proceso. Significa investigar (entrevistas, encuestas), crear prototipos, testear con usuarios reales e iterar. No se diseña para uno mismo ni para 'el cliente imaginario'. Herramientas como mapas de empatía, user personas y journey maps ayudan a entender necesidades y frustraciones. El objetivo es la usabilidad: fácil de aprender, eficiente de usar, agradable. El UCD reduce costos de desarrollo porque se detectan errores temprano. Además, mejora la accesibilidad y la satisfacción. En un mundo con miles de apps, la que mejor resuelve un problema real gana. Pregunta siempre: '¿esto le sirve a quien lo usa?'"},
    {"Construyendo MVPs rápidamente", "Negocios", "Un MVP (Producto Mínimo Viable) no es un producto mal hecho; es la versión más simple que resuelve el problema central de un grupo inicial de usuarios. La clave es identificar la funcionalidad imprescindible (el 'camino feliz') y descartar todo lo demás, incluso características 'bonitas'. Herramientas low‑code (Bubble, Adalo) o frameworks rápidos (Ruby on Rails, Laravel, Next.js) ayudan a lanzar en semanas. El MVP se testea con clientes reales, se recoge feedback y se itera. Fallar rápido y barato es mejor que invertir meses en algo que nadie quiere. Ejemplo: Dropbox empezó con un vídeo explicativo, no con el producto terminado. El MVP es aprendizaje validado, no un lanzamiento definitivo."},
    {"Concurrencia y paralelismo en Java", "Programación", "Concurrencia es tener múltiples tareas en progreso (compartiendo tiempo). Paralelismo es ejecutarlas al mismo tiempo en múltiples núcleos. En Java, desde los clásicos Thread y Runnable hasta el moderno fork/join, ExecutorService, CompletableFuture y las colecciones concurrentes (ConcurrentHashMap). Luego llegaron los virtual threads (Project Loom, disponible desde Java 21) que simplifican enormemente la programación concurrente, permitiendo millones de hilos livianos. Cuidado con condiciones de carrera, deadlocks y visibilidad de memoria (usar volatile, synchronized o clases atómicas). El paralelismo mejora el rendimiento, pero la concurrencia bien gestionada evita bloqueos. Domina el paquete java.util.concurrent."},
    {"Sobre la disciplina diaria", "Personal", "La disciplina es la diferencia entre querer y hacer. No depende de motivación (que es pasajera), sino de rutinas y compromisos pequeños. Por ejemplo, programar 30 minutos cada mañana antes de revisar el móvil. La disciplina se entrena como un músculo: empieza con una sola tarea no negociable (hacer la cama, escribir tres líneas de código). Usa recordatorios visuales y elimina distracciones (notificaciones, escritorio desordenado). También es importante perdonarse cuando fallas y retomar al día siguiente sin culpa. La disciplina no es rigidez: es la libertad de elegir lo que realmente quieres a largo plazo. La constancia vence al talento cuando el talento no es constante."},
    {"Animaciones sutiles en interfaces", "Diseño", "Las animaciones sutiles mejoran la experiencia si no distraen. Una transición suave (ease, no linear) en un menú desplegable indica continuidad. Un efecto hover con cambio de color o leve escala da feedback al usuario. Las animaciones de carga (skeleton screens o spinners) reducen la ansiedad. También se usan para guiar la atención: un botón que late suavemente invita a hacer clic. En web, se logran con CSS (transition, transform, keyframes) y para interacciones complejas, librerías como Framer Motion en React. La regla de oro: duración entre 100 y 300 ms, y no más de 3 movimientos simultáneos. La animación debe tener propósito, no ser un adorno. Menos es más."},
    {"Bases de datos relacionales vs NoSQL", "Tecnología", "Relacionales (MySQL, PostgreSQL) son ideales para datos estructurados, transacciones ACID, joins complejos y consistencia fuerte. Usan esquema fijo. NoSQL abarca varios tipos: documentales (MongoDB), clave‑valor (Redis), columnas (Cassandra), grafos (Neo4j). Escalan horizontalmente fácilmente y manejan grandes volúmenes con esquema flexible o sin esquema. ¿Cuál elegir? Si tu dato es muy relacional y necesitas integridad referencial, ve por SQL. Si tienes datos no estructurados o necesitas alta escritura y lectura con escalabilidad extrema, NoSQL. Muchos proyectos usan ambos (políglota): PostgreSQL para transacciones y Redis para caché. No es una guerra, son herramientas con fortalezas distintas."},
    {"El arte de simplificar el código", "Programación", "Simplificar código no es hacerlo más corto a costa de legibilidad; es eliminar complejidad accidental. Extraer métodos con nombres claros, evitar anidaciones profundas (early returns), reducir parámetros y romper funciones gigantes. También eliminar código muerto y duplicado (DRY). Usar las características del lenguaje sin abusar de ellas. Preferir estructuras de datos simples sobre jerarquías innecesarias de clases. Un código simple es fácil de leer, modificar y depurar. Como dijo Antoine de Saint‑Exupéry: 'La perfección no es cuando ya no hay nada que añadir, sino cuando no hay nada que quitar'. Aplicar refactors pequeños constantemente mantiene la simplicidad viva. El código simple es respetuoso con los compañeros y con tu yo del futuro."},
    {"Cómo cobrar lo que vales", "Negocios", "Cobrar lo que vales empieza por conocer tu valor de mercado. Investiga tarifas en tu sector, experiencia y ubicación. Luego, comunica valor basado en resultados, no en horas. Por ejemplo, cobra por proyecto o por retainer mensual. Evita tarifas por hora que penalizan tu eficiencia. Prepara una propuesta clara: qué entregas, plazos, revisiones y exclusión de alcances extra. Cuando un cliente dice 'es muy caro', pregunta qué presupuesto maneja y negocia alcance, no precio. Aprende a decir 'no' a proyectos que no cumplen tu tarifa mínima. También factura por adelantado (50% o 100%). La seguridad financiera te permite trabajar mejor. Tu trabajo vale, no lo regales."},
    {"Mi setup de desarrollo en 2026", "Tecnología", "En 2026 mi setup es minimalista pero potente: laptop M4 Pro con 32GB RAM, monitor 4K de 32'', teclado mecánico silencioso y trackpad. Editor: VS Code con extensiones para Copilot y dev containers. Terminal: Warp o WezTerm. Para Java uso IntelliJ Ultimate. Docker y Podman para contenedores. También uso un iPad como segunda pantalla o para diagramas. La nube: GitHub Codespaces cuando viajo sin portátil. Lo más importante no son los specs, sino la ergonomía: silla ajustable, escritorio de pie y luces cálidas. La velocidad la da la práctica, no el hardware. Y por supuesto, un gestor de contraseñas y backups automatizados. El setup ideal es el que no te distrae y te permite fluir."},
    {"Mood boards y referencias visuales", "Diseño", "Un mood board es una colección de imágenes, colores, texturas y tipografías que capturan la sensación deseada para un proyecto. Sirve para alinear al equipo y con el cliente antes de empezar a diseñar. Se puede hacer en Pinterest, Miro, Figma o incluso de forma física. Incluir referencias de otras disciplinas (cine, arquitectura, naturaleza) enriquece la creatividad. El mood board no es el diseño final, sino una brújula. Ayuda a evitar desvíos durante el proceso. También es útil para justificar decisiones estéticas. Pasar una hora haciendo un buen mood board ahorra días de revisiones. Es la primera capa del pensamiento visual."},
    {"Documentar antes de construir", "Programación", "Documentar no es escribir novelas; es capturar decisiones clave, arquitectura y contratos. Un pequeño ADR (Architecture Decision Record) explica por qué elegiste MongoDB sobre PostgreSQL. Un diagrama C4 (contexto, contenedores, componentes, código) aclara la estructura. Documentar antes de construir fuerza a pensar en los problemas reales y a comunicar con el equipo. No hace falta documentar cada función (el código debe ser autoexplicativo), pero sí los flujos complejos, las dependencias externas y el setup inicial. La documentación viva (en el repositorio, cerca del código) es más útil que un wiki abandonado. Invertir tiempo en escribir bien es invertir en futuro."},
    {"Aprender en público", "Personal", "Aprender en público significa compartir tu proceso, no solo tus logros. Publica lo que aprendes hoy, aunque sea pequeño: un tweet con un tip, un hilo, un blog post, o incluso un repositorio con ejercicios. Ayuda a fijar conocimientos (enseñar es la mejor forma de aprender), construye tu red profesional y atrae oportunidades. Además, normaliza el error: mostrar que te equivocaste y cómo lo corregiste es valioso para otros. Plataformas: dev.to, LinkedIn, YouTube o tu propio blog. No esperes ser experto; empieza como aprendiz. La comunidad valora la honestidad. Aprender en público también te da responsabilidad para ser consistente. El conocimiento compartido crece."},
    {"Optimización de consultas SQL", "Programación", "Una consulta SQL lenta mata el rendimiento. Estrategias: índices apropiados (B‑tree para búsquedas por igualdad/orden, hash para igualdad, parciales para filtros comunes). Evita SELECT *, trae solo columnas necesarias. Analiza planes de ejecución con EXPLAIN. Descompón subconsultas en JOINs o CTEs. Cuidado con funciones en WHERE (ej. WHERE YEAR(fecha)=2025) porque inutilizan índices; prefiere rangos. Usa paginación con keyset (filtro por id > N) en lugar de OFFSET grande. Normaliza pero sin exceso (desnormalización controlada para reportes). También considera materialized views para agregaciones pesadas. En bases grandes, particionamiento y read replicas. La optimización no es adivinanza: mide, cambia una cosa, vuelve a medir."},
    {"Pricing estratégico para freelancers", "Negocios", "Fijar precios como freelancer es más psicológico que matemático. Evita tarifas por hora porque castigan tu eficiencia. Usa precios por proyecto o por valor (lo que el cliente gana con tu trabajo). Paquetes escalonados: básico, estándar, premium. El efecto ancla: muestra primero el precio más alto para que el medio parezca razonable. También puedes ofrecer retainer mensual por mantenimiento o soporte. Revisa tus precios cada 6‑12 meses. No compitas en precio bajo; compite en calidad, confianza y rapidez. Cuando un cliente te dice 'es caro', pregunta qué presupuesto tiene y ajusta alcance. Tu tiempo vale, tu experiencia vale. Cobra con seguridad y sin disculpas."},
    {"Formularios accesibles", "Diseño", "Un formulario accesible permite que todos, incluyendo usuarios con lectores de pantalla o discapacidad motriz, puedan completarlo. Usa etiquetas HTML <label> asociadas con 'for', no solo placeholders. Agrupa campos relacionados con <fieldset> y <legend>. Indica campos obligatorios visiblemente y ofrece mensajes de error claros (no solo en rojo). El orden de tabulación debe ser lógico. Botones grandes y con suficiente contraste. Para captchas, prefiere alternativas invisibles (honeypot) o reCAPTCHA v3. Añade descripciones ARIA cuando sea necesario, pero no abuses. Prueba con teclado solamente y con herramientas como WAVE. Un formulario accesible no solo es ético, también mejora la tasa de conversión."},
    {"Lecciones de side projects", "Personal", "Los side projects (proyectos personales) son el laboratorio de un creador. Enseñan tecnologías nuevas, gestión del tiempo y lanzamiento de productos. Pero también traen lecciones: empieza pequeño (un MVP de verdad), no te obsesiones con perfección antes de mostrar a alguien. Publica pronto, aunque te dé vergüenza. Muchos side projects mueren porque el autor pierde interés después de la fase divertida (idea inicial). La disciplina de terminar es más valiosa que la idea original. Además, no esperes que sean rentables de inmediato; el aprendizaje es el retorno principal. Comparte lo que construyes, recibe feedback y mejora. Los side projects pueden abrir puertas profesionales inesperadas."}
};

        for (int i = 0; i < data.length; i++) {
            apuntes.add(new Apunte(
                    idCounter.getAndIncrement(),
                    data[i][0],
                    data[i][2],
                    data[i][1],
                    "https://picsum.photos/seed/apunte" + (i + 1) + "/800/1000"));
        }
    }

    public List<Apunte> obtenerTodos() {
        return new ArrayList<>(apuntes);
    }

    public Optional<Apunte> obtenerPorId(Long id) {
        return apuntes.stream()
                .filter(a -> a.getId().equals(id))
                .findFirst();
    }

    public Apunte crear(Apunte apunte) {
        apunte.setId(idCounter.getAndIncrement());
        apuntes.add(apunte);
        return apunte;
    }


    

    public Optional<Apunte> actualizar(Long id, Apunte apunteActualizado) {
        return obtenerPorId(id).map(apunte -> {
            apunte.setTitulo(apunteActualizado.getTitulo());
            apunte.setContenido(apunteActualizado.getContenido());
            apunte.setCategoria(apunteActualizado.getCategoria());
            apunte.setImageUrl(apunteActualizado.getImageUrl());
            return apunte;
        });
    }

    public boolean eliminar(Long id) {
        return apuntes.removeIf(a -> a.getId().equals(id));
    }

    public Optional<Apunte> obtenerPorSlug(String slug) {

    return apuntes.stream()
            .filter(apunte -> slug.equals(apunte.getSlug()))
            .findFirst();
}



}
